{
 "title": "Ping-Admin | World Wide Sites Monitoring",
 "description": "Ping-Admin.com Tasks Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "task_name",
    "label": "Task",
    "query": {
     "query": "label_values(apatit_exporter_refresh_duration_seconds,task_name)"
    }
   },
   {
    "name": "location_name",
    "label": "Location",
    "query": {
     "query": "label_values(apatit_mp_total_duration_seconds{task_name=\"$task_name\"},mp_name)"
    }
   },
   {
    "name": "country_name",
    "label": "Country",
    "query": {
     "query": "label_values(apatit_mp_connect_seconds{task_name=\"$task_name\"},mp_name)"
    }
   },
   {
    "name": "refresh_interval_seconds",
    "label": "Refresh Interval",
    "query": {
     "query": "query_result(apatit_exporter_refresh_interval_seconds)"
    }
   },
   {
    "name": "max_actual_minutes",
    "query": {
     "query": "query_result(apatit_exporter_refresh_interval_seconds/60*apatit_exporter_max_allowed_staleness_steps)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Monitoring Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Locations",
   "type": "stat",
   "description": "Number of Monitoring Points with actual information.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (task_name) (apatit_mp_status{task_name=\"$task_name\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual Problems GEOMap",
   "type": "geomap",
   "description": "Number of problem tasks for each location. The point will be colored according to number problem resources.\n",
   "gridPos": { "h": 16, "w": 22, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum by (mp_name, mp_gps, mp_ip, task_name) (\n    apatit_mp_data_staleness_steps{} * $refresh_interval_seconds / 60\n    ) >= $max_actual_minutes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable Locations",
   "type": "stat",
   "description": "Temporarily unavailable Monitoring Points according to Ping-Admin API.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (task_name) (apatit_mp_status{task_name=\"$task_name\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No Data Locations",
   "type": "stat",
   "description": "Monitoring Points with no data according to Ping-Admin API.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count by (task_name) (apatit_mp_data_status{task_name=\"$task_name\"} == 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Problem Locations Timeline",
   "type": "state-timeline",
   "description": "Intervals when location of any task was unavailable for more than $max_actual_minutes minutes.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sort(\n    (sum by (mp_name, task_name) (\n        apatit_mp_data_staleness_steps{}\n        ) >= 3)\n    /\n    (sum by (mp_name, task_name) (\n        apatit_mp_data_staleness_steps{}\n        ) >= 3)\n)",
     "legendFormat": "{{mp_name}} - {{task_name}}"
    }
   ]
  },
  {
   "title": "Problem Tasks Timeline",
   "type": "state-timeline",
   "description": "Intervals when task had more than 1 failed location (more than $max_actual_minutes minutes of absent data for location).",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort(\n    (count by (task_name) (sum by (mp_name, task_name) (apatit_mp_data_staleness_steps{}) >= 3)) > 1\n)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Task GEOMaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "type": "geomap",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum by (mp_name, mp_gps, mp_ip) (\n    apatit_mp_data_staleness_steps{\n        task_name=\"$task_name\", \n        mp_name=~\"$location_name\"\n        }\n    ) * $refresh_interval_seconds / 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum by (mp_name, mp_gps, mp_ip) (\n  apatit_mp_total_duration_seconds{\n    task_name=\"$task_name\",\n    mp_name=~\"$location_name\"\n  }\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Success Status Update (Minutes Ago)",
     "type": "timeseries",
     "description": "The delay of last success response according to Ping Admin API update",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 437 },
     "targets": [
      {
       "expr": "sum by (mp_name) (\n  apatit_mp_data_staleness_steps{\n    task_name=\"$task_name\",\n    mp_name=~\"$location_name\"\n  }\n) * $refresh_interval_seconds / 60\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Time (Seconds)",
     "type": "timeseries",
     "description": "The total time spent to receive a response from the site (and for tasks with the \"Ping\" type, the response time of the verified address is indicated here).",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (mp_name) (\n  apatit_mp_total_duration_seconds{\n    task_name=\"$task_name\",\n    mp_name=~\"$location_name\"\n  }\n)",
       "legendFormat": "{{tm_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Task Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Last Success Status Update (Minutes Ago)",
   "type": "timeseries",
   "description": "The delay of last success response according to Ping Admin API update.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (mp_name) (\n  apatit_mp_data_staleness_steps{\n    task_name=\"$task_name\",\n    mp_name=~\"$location_name\"\n  }\n) * $refresh_interval_seconds / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Time | Total",
   "type": "timeseries",
   "description": "The total time spent to receive a response from the site (and for tasks with the \"Ping\" type, the response time of the verified address is indicated here).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (mp_name) (\n  apatit_mp_total_duration_seconds{\n    task_name=\"$task_name\",\n    mp_name=~\"$location_name\"\n  }\n)",
     "legendFormat": "{{tm_name}}"
    }
   ]
  },
  {
   "title": "Request Time | DNS",
   "type": "timeseries",
   "description": "The time spent determining the IP address of the site.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (mp_name) (apatit_mp_dns_lookup_seconds{task_name=\"$task_name\", mp_name=~\"$location_name\"})",
     "legendFormat": "{{tm_name}}"
    }
   ]
  },
  {
   "title": "Request Time | Connect",
   "type": "timeseries",
   "description": "The time spent connecting to the site.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (mp_name) (apatit_mp_connect_seconds{task_name=\"$task_name\", mp_name=~\"$location_name\"})",
     "legendFormat": "{{tm_name}}"
    }
   ]
  },
  {
   "title": "Request Time | Server",
   "type": "timeseries",
   "description": "The time spent waiting for the server response (between the connection and the start of data transfer).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (mp_name) (apatit_mp_server_processing_seconds{task_name=\"$task_name\", mp_name=~\"$location_name\"})",
     "legendFormat": "{{tm_name}}"
    }
   ]
  },
  {
   "title": "Lack of Data",
   "type": "state-timeline",
   "description": "Monitoring Points with no data according to Ping-Admin API.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum by (mp_name) (apatit_mp_data_status{task_name=\"$task_name\"} == 0)",
     "legendFormat": "{{mp_name}}"
    }
   ]
  },
  {
   "title": "Miscellaneous",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter | Unavailable Monitoring Points",
     "type": "state-timeline",
     "description": "Temporarily unavailable Monitoring Points according to Ping-Admin API.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 192 },
     "targets": [
      {
       "expr": "sum by (mp_name) (apatit_mp_status{} == 0)",
       "legendFormat": "{{mp_name}}"
      }
     ]
    },
    {
     "title": "Exporter | Number of Available Monitoring Points",
     "type": "timeseries",
     "description": "Available Monitoring Points.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 199 },
     "targets": [
      {
       "expr": "count by (task_name) (apatit_mp_data_staleness_steps{task_name=\"$task_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporter | API Request Time",
     "type": "timeseries",
     "description": "Exporter request time to Ping-Admin API.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 207 },
     "targets": [
      {
       "expr": "sum by (task_name) (apatit_exporter_refresh_duration_seconds)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task | Monitoring Point Availability",
     "type": "timeseries",
     "description": "Will be zero if service is unavailable according to API data or it was responded more than 24h ago.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 214 },
     "targets": [
      {
       "expr": "sum by (mp_name) (apatit_mp_status{mp_name=~\"$location_name\", task_name=\"$task_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task | Request Speed",
     "type": "timeseries",
     "description": "Request Speed according to Ping-Admin API response.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (mp_name) (apatit_mp_speed_bytes_per_second{task_name=\"$task_name\", mp_name=~\"$location_name\"})",
       "legendFormat": "{{tm_name}}"
      }
     ]
    }
   ]
  }
 ]
}